version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8083:8083'
    environment:
      ME_CONNECTION_STRING: mongodb://mongo:27017
      DATABASE_NAME: comp3123_assignment1
      PORT: 8083
      MONGO_DB_USERNAME: admin
      MONGO_DB_PASSWORD: password
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
