version: '3.8'

services:
  app:
    build: .
    ports:
      - '8083:8083'
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/mydatabase
    volumes:
      - .:/usr/src/app

  mongo:
    image: mongo:4.4
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'

  mongo-express:
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    ports:
      - '8082:8081' 
    depends_on:
      - mongo

volumes:
  mongo-data:
